# Meetings

## 03/02/23 Meeting with Claudia
- For later: QUaltrics vehicle circle checks dashboard for Claudia

- Talk to Chris about what you need server wise:
  1. Running a database (MySQL or something like that)
    - I'd have to write a program to pull data from Megamation's API. 
    - Max load of API is 50 mb, and max request duration is 2 minutes. Fine.
    -  Benefit: being able to directly interface to new (e.g. 2023) data, so that processes can be completely independent. No need for automatic emails from Li and manually updating folders on a shared drive.
    - Recall Megamation's SQL option is 10s of thousands of dollars more per year.
  2. Running R to host our own Shiny server. 


- Union codes in year to year summary.

Multy Year Summary of Employee Union Days. 
Codes with all the ones with Leave in description.

Ask Andrew for Data folder on G drive. and subfolders.

Unions have different rules.

---

Time off in lieu. They can accrue up to 40hrs, then use it as a day off. And again and again. 

Claudia: they don't just have 40 a year, they can have 80 if they rebank and use it and rebank it. This is for when someone works overtime and we dont pay out overtime. Claudia is wondering what if we just paid the overtime, as currently we are losing work hours.

CUPE does not have TOILS(tat). For stat holiday they just use TOILB(ank).

We are interested in the last 5 years (not so much 2023).

We can sum the TOILB (just 1x), TB 1.5x, TB 2x...

PK 1.5x or PM 2x PJ 1x is used when TOILB is about to go over 40.  TOILP is when someone asks for the payout from TOILB. We can't sum PK, PM and PJ with TOILB as Px is used for other reasons than time off in lieu.

Need to include WETB. Because WETB goes into TOILB and then TOILP to pay it out. We don't have a WETP.

Need to also sum by FRT.

So 4 reports: Union leave, TOILB sums per year and crew CUPE MES and CUST, FRT, and Px. All in multi-year report.

---

We will have a meeting to standardize work order descriptions.



## 02/12/23 Meeting with Chris and Steph

- Payroll: we want some automated tools. Might satisfy Kristen and Claudia's needs. 
- The questions Steph has asked for all of Jan. might get us there. 
- Screens for checking and testing exist (for Steph'account): Mobile Hour Balance.
  - MOBILE -- Modules: Employee Timekeeping: Export Reports: Mobile Hour Balance Report: 
   - entries not yet approved by staff members? Date is last time Sync happened? January 11th: the day we hit the button.
  
  - DIRECT LINE -- Module: Employees: Reports: Hour Balance Report. 
  - Click Details. Run until end of year. All employees
  - This shows employee per row.
  - Task: pivot this wider by code, and check if the numbers for the units match the Mobile report. 
  
  Only compare fields in the mobile. 


## 02/02/23 Meeting with Claudia and Kristen

### Report gt16

- Done: Brown 1 day 44 hours? See raw data as the others are fine
- One day, let's be able to have all sick, and filter for any number of days per year.
- Label departments
- What are the numbers in grey? Add a legend. They are rows of occasions.
- Add:
    - Current Crew (most up to date, could use last date or use actual employee data)
    - Start date, first name, # occasions, groupings of departments (Claudia will give these; e.g. which fall under Custodial; or can be inferred from the labels)
    - Add a Vacation tab, then another tab on X...
    - Date filter

### Find inspiration

Claudia and I will go to Fanshawe to see how Rich (data scientist educated by Cornell) does a demo of ClickView for their facilties data analysis.

### CUPE Sick Reporting 2015-2020

Reproduce Excel sheets called "Summ - 5YR History", add employee number and current crew.

## 12/22/22 Meeting with Claudia

1.  We can design dashboards in the new year on a whiteboard
2.  HR
    -   Turnover: how many started in year; left in a year

    -   Stephany puts them on LTD; how many days of absence in LTD

    -   Sick after 90 days does not get recorded; they then go on STD

    -   total number of (WORK) days sick

    -   Covid sick

        -   \# occasions is particularly important, filter for \> 1

            -   \# days for these people

            -   picking top 10% - AS: this can be selectable

    -   Occurrence

        -   2 from Jan-June end

        -   2 from July - Dec end

        -   How many days are they using for every occurrence?

        -   Where there are weekends in between sick days, count as one instance but only count the work days --- Exceptions:

            -   2 people who work weekends; they can be exceptions..

            -   with Steve

                -   shift work in maintenance building mechanics may also be exceptions

                -   CUP: central utility plant people (Crew); funny shedule 5 days on, off ,et c.

    -   Adding logic to detect trends

        -   March madness: sick time

        -   Superbowl
3.  Steve, etc. will ask for more things; they will need to be in a queue; and whether they can jump the queue


## 01/05/22 Meeting With Evan

**PPPE - Inventory Report.xlsx - Evan thinks 2023 may be the last year we do this**

1.  Inventory Report - high level

2.  Should we use FRS or Stockroom; Non-Chargeable (we provide it) PPE Total is 20k, closest to Dave number

3.  Chargeable is what we charge the campus, we get the money back

4.  Matt's number for NC PPE is 17k because of his corrections; COVID non-chargeable is basically masks

5.  Claudia forecasting spending 671k

6.  UOG PPE Inv Category: part numbers for PPE Category;

7.  UOG Inv Issue Usage By Class, filter on class of part, look for wording of PPPE in Class column -- Issue is " can I get some X", Stock issue, track outflow of inventory, requisition is incoming, issuance is outgoing

    1.  Unit is matched department (basically data dictionary)

8.  Requisition

    1.  Ordered vs Received (Received can be lower if stock was limited so only a bit was received)

    2.  Date is Ordered date.

    3.  Currently each row has a unique requisiton number; would need to check for duplicates if we use mutliple requisition dates

9.  External QTY does not have number of units (number of gloves) as we don't have this, we only have part numbers and we never thought it was worth the effort to find out number of gloves

## 01/05/22 Meeting With Claudia

1.  **Ask Chris whether Megamation can host a webserver for our applications**
2.  Megamation not providing correct emp-trans report data themselves. In case this CSV option does not work well, should we also explore the alternative HTTP web API solution in the mean-time? Li mentioned that R supports it very well. I would have to write up code to connect to it and retrieve data.
    1.  Ask Chris and Lee to get this going, have a call, it is urgent

    2.  Claudia has not seen any quote from Mario/Lee on the CSV automatic file creation
3.  **The booklet, how to book rooms for quiet**
4.  **HR insurance**
5.  CUPE:
    1.  Qualtrics on compliance reporting (Anne Macdonald - Viki - PR Training Account)

        1.  vehicle inspections

        2.  elevated platform inspection checklist

        3.  fall arrest

        4.  snow

    2.  Anne: Millright trade certificate: workers opinion is that good work is being contracted out and people are not happy

        1.  What jobs are being assigned; how many people are plunging toilets vs replacing pipes; can take to Steve with the results; use keywords of work order descriptions

    3.  **Occurrences**:

        1.  Jan-June 30th : 2 times (every 6 months). HR reports should be sent back if someone was sick a 3rd time (**occurrence**)

            1.  but some people were slipping through

            2.  problem: for 1st occasion, they don't get paid at all

    4.  Bereavement: 7 days of **bereavement** in a row is not allowed; most is 5 days for family

        1.  We need to know when someone is taking too many bereavement days

    5.  **Sick analysis**

        1.  for Dan Brown; had a lot of sick time; came back in 2022; is his sick time the same regardless of nights and days; he said nights were aggravating his sickness; but he still took days off as if days aggravate him as well; we need to test/show whether day/night shifts are not helping so that when we talk to him, he can be aggravated into leaving his position and repositioned; find his employee number

        2.  from 2017 - present

        3.  short term sick; ltd after 3 months of this; perm ltd after 2 years

        4.  Rachelle Videka

        5.  Caitlyn Flynn

        6.  Ganece Thomson (from 2015)

        7.  Kitty Stevenson
6.  Look at CV instances.xlsx
7.  Why Claudia likes Megamation: we were one of their first clients; they provide excellent support which other companies like A-something do not and sometimes provide 0 support
8.  **Let Claudia know every time someone asks me for something to help me prioritize**
